### ISSUE TITLE
refactor: manifest format

### ISSUE THREAD

**Issue by rumblefrog** [sourcemod-dev/manifest#1]
Historical manifest formats need to be converted into the new TOML format for support of chronicles.

Example TOML:

```toml
[meta]
name = "core"
description = "sourcemod core"
author = "n/a"

[source]
type = "git"
repository = "https://github.com/alliedmodders/sourcemod.git"
patterns = [
	"plugins/include/*.inc"
]
```

Specification of available keys & sections are in https://github.com/rumblefrog/sp-docgen/blob/e65fc2ffa077b5ed34928623d1e72b67104ab16d/libschema/src/manifest.rs
